# Generated by Django 3.1.2 on 2021-02-06 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lotusemployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('managerid', models.IntegerField(null=True)),
                ('username', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'permissions': [('is_manager', 'Can see employee'), ('is_employee', 'Can see self')],
            },
        ),
        migrations.CreateModel(
            name='reportdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=255)),
                ('workdesc', models.TextField(null=True)),
                ('otherwork', models.TextField(null=True)),
                ('otherworkdesc', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=500)),
                ('undonework', models.CharField(blank=True, max_length=128, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('managerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.lotusemployee')),
                ('username', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'dailyreport_reportdetails',
            },
        ),
    ]
